/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 37fb27bb6993ddc6b1bc65ed619392db)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/worker')
  }
  interface Env {
    POLAR_MODE: string
    SUCCESS_URL: string
    POLAR_ACCESS_TOKEN: string
    POLAR_WEBHOOK_SECRET: string
    ASSETS: Fetcher
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, 'POLAR_MODE' | 'SUCCESS_URL' | 'POLAR_ACCESS_TOKEN' | 'POLAR_WEBHOOK_SECRET'>> {}
}
